<a href="https://colab.research.google.com/github/iformigoni/Entrada_Publica/blob/main/polinomiais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import control
import numpy as np
# import matplotlib.pyplot as plt

a = [1,5]
print(a)
print(np.roots(a))

b = [1,4,20]
print(b)
print(np.roots(b))

# print(np.sin(np.pi))

c = np.poly([-1,-3,-10])
print(c)
print(np.roots(c))

# 3*(s+5) = 3s+15
print(3 * np.array([1,5]))


# a = np.array([0,1,5])
# b = np.array([1,4,20])
# print(a+b)


#conv(a,b)

d = np.convolve(a,b)
print(d)
e = [1,0]
f = np.convolve(d,e)
print(f)
print(np.roots(f))
print(np.poly([0,-5,-2+4j,-2-4j]))

[1, 5]
[-5.]
[1, 4, 20]
[-2.+4.j -2.-4.j]
[ 1. 14. 43. 30.]
[-10.  -3.  -1.]
[ 3 15]
[  1   9  40 100]
[  1   9  40 100   0]
[-5.+0.j -2.+4.j -2.-4.j  0.+0.j]
[  1.   9.  40. 100.   0.]
